version: '3.8'
services:
  contelix-services:
    build: packages/services
    restart: always
    depends_on:
      - mongo
      - minio
    ports:
      - 3001:3001
    volumes:
      - services-volume:/cache/multer
    environment:
      PORT: 3001
      HOSTNAME: contelix-services
      CACHE_MULTER: /cache/multer
      JWT_KEY:  changeme
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_USE_SSL: false
      MINIO_PORT: 9000
      MINIO_END_POINT: minio 
      MINIO_BUCKET: contelix
      MONGO_CONNECTION_STRING: mongodb://mongoUser:mongoPass@mongo:27017
      MONGO_DATABASE_NAME: contelix
      MONGO_IMAGES_COLLECTION_NAME: posts
  contelix_ui:
    build: packages/ui
    restart: always
    depends_on:
      - contelix-services
    ports:
      - 3000:3000
    environment:
      BASE_PATH_SERVICES: http://contelix-services:3001
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-volume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoUser
      MONGO_INITDB_ROOT_PASSWORD: mongoPass
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoUser
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongoUser
      ME_CONFIG_MONGODB_URL: mongodb://mongoUser:mongoPass@mongo:27017/
  minio:
    image: quay.io/minio/minio
    restart: always
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio-volume:/data
    command: server /data --console-address ":9001"

volumes:
  minio-volume:
  mongo-volume:
  services-volume:
