version: '3.8'
services:
  minio:
    image: quay.io/minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio-volume:/data
    command: server /data --console-address ":9001"

volumes:
  minio-volume:
